# Generated by Django 3.2.4 on 2021-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGWEB', '0003_auto_20210622_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
        ),
    ]
