# Generated by Django 3.2.4 on 2021-06-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGWEB', '0006_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='compras',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
