# Generated by Django 3.2.4 on 2021-07-01 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGWEB', '0008_auto_20210701_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 1)),
        ),
    ]
