# Generated by Django 3.2.4 on 2021-07-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAGWEB', '0010_alter_carrito_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.SmallIntegerField(default=1),
        ),
    ]
