# Generated by Django 3.2.4 on 2021-07-04 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JAGWEB', '0011_carrito_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.CreateModel(
            name='Renglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('producto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JAGWEB.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JAGWEB.renglon'),
        ),
    ]
