# Generated by Django 3.2.4 on 2021-07-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAGWEB', '0013_auto_20210703_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renglon',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='renglon',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Renglon',
        ),
    ]
